package com.example.roadmaintenance

const val REMEMBER_ME = "REMEMBER_ME"
const val ID = "ID"
const val USERNAME = "USERNAME"
const val PASSWORD = "PASSWORD"
const val USER_PREFERENCES = "USER_PREFERENCES"
const val SEND_PATHWAY = "SEND_PATHWAY"
const val SEND_SELECTED_PATHWAY = "SEND_SELECTED_PATHWAY"
const val SEND_PATHWAY_LIST = "SEND_PATHWAY_LIST"
const val RESTORE_PATHWAY_LIST = "RESTORE_PATHWAY_LIST"
const val RESTORE_PATHWAY = "RESTORE_PATHWAY"
const val RESTORE_POLYLINE_LIST = "RESTORE_POLYLINE_LIST"