package com.example.roadmaintenance

const val REMEMBER_ME = "REMEMBER_ME"
const val ID = "ID"
const val USERNAME = "USERNAME"
const val PASSWORD = "PASSWORD"
const val USER_PREFERENCES = "USER_PREFERENCES"
const val TRANSPORTATION_DATABASE = "TRANSPORTATION_DATABASE"
const val TRANSPORTATION_TABLE = "TRANSPORTATION_TABLE"