package com.example.roadmaintenance

const val REMEMBER_ME = "REMEMBER_ME"
const val ID = "ID"
const val USERNAME = "USERNAME"
const val PASSWORD = "PASSWORD"
const val USER_PREFERENCES = "USER_PREFERENCES"
const val REQUEST_KEY_PASS_DATA_TO_LIGHT_POST = "REQUEST_KEY_PASS_DATA_TO_LIGHT_POST"
const val REQUEST_KEY_PASS_PATHWAY = "REQUEST_KEY_PASS_PATHWAY"